imports:
- path: gcpHttpLb.py

resources:
- name: frontend
  type: gcpHttpLb.py
  properties:
    zone: us-west1-b
    port: 80
    service: http
    region: us-west1
    lbscope: EXTERNAL
    lb_port: <LB PORT>
    ig_network_cidr: < CIDR of internal network>
    project_id: < Project ID>
    instance : <instance name>